### ISSUE TITLE
Pure question post: Questions about inference

### ISSUE THREAD

**Issue by xujinbao282** [huanngzh/Parts2Whole#7]
During the inference process, is it supported to be used in combination with human LoRA? 
If it is supported, is there a simple usage example?

**Comment by huanngzh** [comment]
Since our method requires fine-tuning UNet, the model will lose some generalization. Therefore, it is foreseeable that the model will not perform well after combining with human LoRA in the inference stage. We are currently considering the design of the adapter (to support existing LoRA, etc.), so stay tuned.
